### ISSUE TITLE
[Bug] Unblurred images and info lost after next refresh(s)

### ISSUE THREAD

**Issue by n00b42** [tajnymag/tinder-deblur#27] opened 2023-05-15 15:10 UTC
It seems that after the first `unblur()` and the next (or one after that) `updateUserInfos` all profiles are shown.
But after another iteration the images for some of the profiles (third-last) are gone (black), and after another iteration the info text is gone as well.

~~~
timeline:
console log "unblur","updateUserInfos" => blurred are gone
sleep
console log "unblur","updateUserInfos" => unblurred profiles with images and info are shown
sleep
console log "unblur","updateUserInfos" => some image go black
sleep
console log "unblur","updateUserInfos" => profiles with black images loose description/text as well.
~~~

Tested with Version 4.0

**Comment by gavracone** [comment] 2023-05-16 13:44
I have 14+ likes
When i open "likes" page, i see blured images and 2,3 seconds later all of them gone and i have empty page.
Refresh doesnt help.

**Comment by tajnymag** [comment] 2023-05-16 14:46
@JustixDevelopment

Perhaps something related to removing "fake" profiles?

**Comment by jgeramb** [comment] 2023-05-16 14:49
That would require the api response to change though, I’ll test a few things later.

**Comment by jgeramb** [comment] 2023-05-17 16:16
@tajnymag #29 should give us more info

**Comment by jgeramb** [comment] 2023-05-17 16:18
@gavracone please check if the issue persists with the latest dev version: https://github.com/tajnymag/tinder-deblur/raw/develop/tinder.user.js

**Comment by imongithub123** [comment] 2023-05-17 16:31
is it supposed to be different now? in the sense that instead of clicking on likes and it unblurring, now the screen goes black and then shows them in a slightly different format

**Comment by naoliv** [comment] 2023-05-17 18:01
> @gavracone please check if the issue persists with the latest dev version: https://github.com/tajnymag/tinder-deblur/raw/develop/tinder.user.js

Just tested it and thumbs get black after a while.

**Comment by gavracone** [comment] 2023-05-17 18:48
> @gavracone please check if the issue persists with the latest dev version: https://github.com/tajnymag/tinder-deblur/raw/develop/tinder.user.js

On FF all thumbs are blured and all gone after 1,2 seconds but one stay with messege "invalid"
On CHrome, thumbs are still blured and all gone after 1,2 seconds.

**Comment by imongithub123** [comment] 2023-05-17 19:33
yup, doesnt work well

**Comment by n00b42** [comment] 2023-05-17 21:07
Firefox 113.0.1 (64bit)
The new version works way better for me.

Temporary video links (deleted after 5d)
- https://tempclip.com/CMOMkV71rhATdUf/watch
- with console open: https://tempclip.com/B4paCfAlbZX04Er/watch

**Comment by jgeramb** [comment] 2023-05-17 21:42
Looks similar to me @n00b42 .
Here's how it looks to me with both Firefox (version 113.0.1) and Chrome (Brave v1.51.118): https://streamable.com/v81n4u

@imongithub123 @gavracone @naoliv could you please clear your browser data or disable cache via DevTools and try again with this alpha version: https://gist.github.com/JustixDevelopment/dcb9766e8bc5f7a4d0b3a14c85079cea/raw/05c2ec4333191a51ad7b48bdd1d39794b44d6f42/tinder.user.js

**Comment by naoliv** [comment] 2023-05-17 22:17
Yep, it did work with cache disabled.
And I could even match or discard even without having Tinder gold.
Fantastic!

**Comment by naoliv** [comment] 2023-05-17 22:25
Just one doubt: after discarding/matching some contacts, it only stays like this:

![](https://github.com/tajnymag/tinder-deblur/assets/982338/a932cbf2-2c49-4b72-946c-5a3ee6306294)

And it doesn't load anything else anymore.
It means that basically all that 17 likes are from fake Tinder profiles?

Edit:

_Sometimes_ it loads like this:

![](https://github.com/tajnymag/tinder-deblur/assets/982338/471312f9-639f-42f5-888a-2cf615ed916c)

**Comment by imongithub123** [comment] 2023-05-17 22:41
yeah and it doesnt seem to be loading different people like it used to. i feel like im seeing the same faces.

**Comment by jgeramb** [comment] 2023-05-17 23:02
> yeah and it doesnt seem to be loading different people like it used to. i feel like im seeing the same faces.

This is because of Tinder, they changed their API so that it always returns the same 10 teasers now.
Also, I have noticed that I have more likes than the app/website tells me since I once had a match with someone that was not in the teasers and I had exactly 10 likes at that point.

**Comment by jgeramb** [comment] 2023-05-17 23:03
> Just one doubt: after discarding/matching some contacts, it only stays like this:
> 
> ![](https://user-images.githubusercontent.com/982338/239090297-a932cbf2-2c49-4b72-946c-5a3ee6306294.png)
> 
> And it doesn't load anything else anymore. It means that basically all that 17 likes are from fake Tinder profiles?
> 
> Edit:
> 
> _Sometimes_ it loads like this:
> 
> ![](https://user-images.githubusercontent.com/982338/239091273-471312f9-639f-42f5-888a-2cf615ed916c.png)

Okay so I'll show a different message if there are no likes left. Like I already explained in the comment above, even if you disliked/liked all 10 teasers, you will most likely see the same teasers over and over again.

**Comment by jgeramb** [comment] 2023-05-17 23:26
@naoliv @imongithub123 here would be the new version with the "no likes available" message: https://gist.github.com/JustixDevelopment/29747f682a30377f2e2f9d9cd869aae5/raw/600d6ee3c4adeb9a8951c785578d834b5f329eda/tinder.user.js

**Comment by imongithub123** [comment] 2023-05-18 01:53
thanks, unfortunately it's not as good as it was a few days ago

**Comment by jgeramb** [comment] 2023-05-18 07:28
@imongithub123 could you explain what is not working as expected?

**Comment by imongithub123** [comment] 2023-05-18 10:16
At the moment, I still see one "invalid" on my screen

**Comment by imongithub123** [comment] 2023-05-18 10:20
Though, it's great to be able to match with the person you see now just by clicking the heart. Unfortunately once the you do everyone on the page, even if you have more likes, it won't show anyone new.

**Comment by imongithub123** [comment] 2023-05-18 10:30
This is the only issue for me now


<img width="1204" alt="Screen Shot 2023-05-18 at 6 29 39 AM" src="https://github.com/tajnymag/tinder-deblur/assets/110348663/a5c1bad6-caad-479b-9fec-58f931b15711">

**Comment by tajnymag** [comment] 2023-05-18 10:51
Justix came up with a new batch of fixes, could you please test it and let us know?

https://github.com/tajnymag/tinder-deblur/raw/develop/tinder.user.js

**Comment by imongithub123** [comment] 2023-05-18 10:53
Still have the same problems, sadly. Just one showing that is 'invalid'

**Comment by tajnymag** [comment] 2023-05-18 10:54
> Still have the same problems, sadly. Just one showing that is 'invalid'

Even after cleaning page data+cache?

**Comment by jgeramb** [comment] 2023-05-18 10:55
> Though, it's great to be able to match with the person you see now just by clicking the heart. Unfortunately once the you do everyone on the page, even if you have more likes, it won't show anyone new.

Well as I already said, we can’t do anything about that since the script relies on the Android API. They sadly changed it so that it only returns the first 10 likes, even if you disliked them. The „invalid“ tag means that the teaser has a url which cannot be unblurred since it doesn’t contain the user id.

**Comment by imongithub123** [comment] 2023-05-18 10:57
Clearing cache shows me the same faces like you said. Any chance I'll see different people and how long does that take?

**Comment by jgeramb** [comment] 2023-05-18 10:59
I can’t give you any information about that because only Tinder knows how the teasers are chosen, sorry.

**Comment by imongithub123** [comment] 2023-05-18 11:06
All good, thank you

**Comment by imongithub123** [comment] 2023-05-18 22:07
Screen is stuck on loading unfortunately.

<img width="1121" alt="Screen Shot 2023-05-18 at 6 06 38 PM" src="https://github.com/tajnymag/tinder-deblur/assets/110348663/603d2675-84ea-40c6-b88a-94e2bdb9f474">

**Comment by n00b42** [comment] 2023-05-19 09:33
> https://github.com/tajnymag/tinder-deblur/raw/develop/tinder.user.js

Yesterday I had the impression it still worked.
Today I got 403 when fetching user info.
~~~
11:30:38.192 [TINDER DEBLUR]: Removing Tinder Gold ads [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
11:30:38.194 [TINDER DEBLUR]: Checking filters [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
11:30:38.195 [TINDER DEBLUR]: Deblurring likes [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
11:30:38.437 [TINDER DEBLUR]: Updating user infos [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
11:30:38.446
XHRGET
https://api.gotinder.com/user/5b7067ad3dd8e90431b4304d
[HTTP/2 403 Forbidden 119ms]

11:30:38.447
XHRGET
https://api.gotinder.com/user/5f3bd86deb6dee0100730053
[HTTP/2 403 Forbidden 304ms]

11:30:38.447
XHRGET
https://api.gotinder.com/user/5dbf69bbda3fe50100bd1026
[HTTP/2 403 Forbidden 124ms]

11:30:38.448
XHRGET
https://api.gotinder.com/user/6250815cf7772f010009b183
[HTTP/2 403 Forbidden 123ms]

11:30:38.449
XHRGET
https://api.gotinder.com/user/63a98ee0d7fd080100cdb567
[HTTP/2 403 Forbidden 304ms]

11:30:38.449
XHRGET
https://api.gotinder.com/user/63464fc3f715420100218036
[HTTP/2 403 Forbidden 123ms]

11:30:38.450
XHRGET
https://api.gotinder.com/user/63f687e8009c3c0100f839ba
[HTTP/2 403 Forbidden 307ms]

11:30:38.587
Could not load user '5b7067ad3dd8e90431b4304d' [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
11:30:38.593
Could not load user '6250815cf7772f010009b183' [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
11:30:38.600
Could not load user '63464fc3f715420100218036' [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
11:30:38.603
Could not load user '5dbf69bbda3fe50100bd1026' [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
11:30:38.782
Could not load user '5f3bd86deb6dee0100730053' [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
11:30:38.784
Could not load user '63a98ee0d7fd080100cdb567' [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
11:30:38.790
Could not load user '63f687e8009c3c0100f839ba'
~~~

**Comment by tajnymag** [comment] 2023-05-19 09:41
> > https://github.com/tajnymag/tinder-deblur/raw/develop/tinder.user.js
> 
> Yesterday I had the impression it still worked. Today I got 403 when fetching user info.
> 
> ```
> 11:30:38.192 [TINDER DEBLUR]: Removing Tinder Gold ads [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
> 11:30:38.194 [TINDER DEBLUR]: Checking filters [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
> 11:30:38.195 [TINDER DEBLUR]: Deblurring likes [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
> 11:30:38.437 [TINDER DEBLUR]: Updating user infos [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
> 11:30:38.446
> XHRGET
> https://api.gotinder.com/user/5b7067ad3dd8e90431b4304d
> [HTTP/2 403 Forbidden 119ms]
> 
> 11:30:38.447
> XHRGET
> https://api.gotinder.com/user/5f3bd86deb6dee0100730053
> [HTTP/2 403 Forbidden 304ms]
> 
> 11:30:38.447
> XHRGET
> https://api.gotinder.com/user/5dbf69bbda3fe50100bd1026
> [HTTP/2 403 Forbidden 124ms]
> 
> 11:30:38.448
> XHRGET
> https://api.gotinder.com/user/6250815cf7772f010009b183
> [HTTP/2 403 Forbidden 123ms]
> 
> 11:30:38.449
> XHRGET
> https://api.gotinder.com/user/63a98ee0d7fd080100cdb567
> [HTTP/2 403 Forbidden 304ms]
> 
> 11:30:38.449
> XHRGET
> https://api.gotinder.com/user/63464fc3f715420100218036
> [HTTP/2 403 Forbidden 123ms]
> 
> 11:30:38.450
> XHRGET
> https://api.gotinder.com/user/63f687e8009c3c0100f839ba
> [HTTP/2 403 Forbidden 307ms]
> 
> 11:30:38.587
> Could not load user '5b7067ad3dd8e90431b4304d' [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
> 11:30:38.593
> Could not load user '6250815cf7772f010009b183' [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
> 11:30:38.600
> Could not load user '63464fc3f715420100218036' [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
> 11:30:38.603
> Could not load user '5dbf69bbda3fe50100bd1026' [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
> 11:30:38.782
> Could not load user '5f3bd86deb6dee0100730053' [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
> 11:30:38.784
> Could not load user '63a98ee0d7fd080100cdb567' [24127-64ba88edef2b332fe902.js:2:32651](https://tinder.com/static/build/24127-64ba88edef2b332fe902.js)
> 11:30:38.790
> Could not load user '63f687e8009c3c0100f839ba'
> ```

I really hope we didn't get Tinder to change the API

**Comment by imongithub123** [comment] 2023-05-19 12:36
Looks like there isn't a fix at the moment?

**Comment by hoesman** [comment] 2023-05-20 10:46
I have been using my own php tinder script, to show recommendations, likes, view profiles, and everything works except for getting the user profile since yesterday returning 403 Forbidden as mentioned above, trying to figure it out with no success, the same url works when accessing from tinder.com, I guess something wrong with headers?

this is what curl returns
`
< HTTP/1.1 403 Forbidden
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Date: Sat, 20 May 2023 10:37:46 GMT
< content-encoding: gzip
< vary: Accept-Encoding
< X-Request-ID: removed
< X-Cache: Error from cloudfront
< Via: 1.1 5da47734f496c05ba90c546c024fb778.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: LHR61-C2
< X-Amz-Cf-Id: removed
< 
Connection #13 to host api.gotinder.com left intact
{"status":403,"error":"Forbidden"}
`

**Comment by jgeramb** [comment] 2023-05-20 13:29
After further investigation I can confirm that the API was changed, the platform header no longer has any effect and we only get fake user ids back. It's been a great time, thank you all for your loyality to the script and especially @tajnymag for making this possible at all!

**Comment by hoesman** [comment] 2023-05-20 13:52
Are you sure? I get valid user ids on "/v2/fast-match/teasers" the only problem is "/user/_ID" returning 403 Forbidden for me.

By inspecting network on tinder.com it retrieves the user, when I replace the user id and resend it returns 403, only thing that seems to change is from Sec-Fetch-Mode: cors to Sec-Fetch-Mode: no-cors if that matters..

**Comment by anilabhadatta** [comment] 2023-05-20 13:53
@JustixDevelopment https://github.com/ecole96/TinderUnblur/tree/master
refer to this repo, it is working

**Comment by imongithub123** [comment] 2023-05-20 14:08
i dont think the api was changed

**Comment by jgeramb** [comment] 2023-05-20 14:12
> @JustixDevelopment https://github.com/ecole96/TinderUnblur/tree/master refer to this repo, it is working

well this is because this is using a different approach to unblur the images, this will only work for 1 image though, I could implement that using the following code:
`teaserEl.style.backgroundImage = `https://preview.gotinder.com/${teaser.user._id}/original_${teaser.user.photos[0].id}.jpeg`;`

**Comment by tajnymag** [comment] 2023-05-20 14:17
We might have to go back to the roots

**Comment by jgeramb** [comment] 2023-05-20 14:28
> Are you sure? I get valid user ids on "/v2/fast-match/teasers" the only problem is "/user/_ID" returning 403 Forbidden for me.
> 
> By inspecting network on tinder.com it retrieves the user, when I replace the user id and resend it returns 403, only thing that seems to change is from Sec-Fetch-Mode: cors to Sec-Fetch-Mode: no-cors if that matters..

The user id is valid, but it is not the real user id.
Have a look at this, I show the result using a real user id from a match and the one returned from the Android api: https://streamable.com/fjc7l7

**Comment by jgeramb** [comment] 2023-05-20 14:31
> i dont think the api was changed

as you can see in my comment above, it was

**Comment by jgeramb** [comment] 2023-05-20 14:32
> We might have to go back to the roots

yup, we have to remove like 80% of the script sadly

**Comment by hoesman** [comment] 2023-05-20 14:34
> > Are you sure? I get valid user ids on "/v2/fast-match/teasers" the only problem is "/user/_ID" returning 403 Forbidden for me.
> > By inspecting network on tinder.com it retrieves the user, when I replace the user id and resend it returns 403, only thing that seems to change is from Sec-Fetch-Mode: cors to Sec-Fetch-Mode: no-cors if that matters..
> 
> The user id is valid, but it is not the real user id. Have a look at this, I show the result using a real user id from a match and the one returned from the Android api: https://streamable.com/fjc7l7

the user id is the real id, you arent getting any result because the /user/_ID endpoint is returning 403 on any user id you fetch

**Comment by jgeramb** [comment] 2023-05-20 14:36
> > > Are you sure? I get valid user ids on "/v2/fast-match/teasers" the only problem is "/user/_ID" returning 403 Forbidden for me.
> > > By inspecting network on tinder.com it retrieves the user, when I replace the user id and resend it returns 403, only thing that seems to change is from Sec-Fetch-Mode: cors to Sec-Fetch-Mode: no-cors if that matters..
> > 
> > 
> > The user id is valid, but it is not the real user id. Have a look at this, I show the result using a real user id from a match and the one returned from the Android api: https://streamable.com/fjc7l7
> 
> the user id is the real id, you arent getting any result because the /user/_ID endpoint is returning 403 on any user id you fetch

i literally just showed in the video that it doesn't?!

**Comment by hoesman** [comment] 2023-05-20 14:39
Try fetching a "REAL" id on https://api.gotinder.com/user/, you GET 403 for any id, except when you fetch it via tinder.com

**Comment by jgeramb** [comment] 2023-05-20 14:44
Well since we do fetch it from tinder.com with this script, it doesn't matter if the referer must be tinder.com. Fetching real ids works fine for me, just not the ones from the teasers.

![Screenshot (000201)](https://github.com/tajnymag/tinder-deblur/assets/30385979/04f5603a-73c6-4c9b-bd07-472b151659ee)

**Comment by hoesman** [comment] 2023-05-20 15:02
I have logged real ids from swipes from few days ago, and they dont work, I dont know anymore

**Comment by jgeramb** [comment] 2023-05-20 15:13
> I have logged real ids from swipes from few days ago, and they dont work, I dont know anymore

I can confirm that swipe ids also don't work, it looks like they restrict the user endpoint to matches.

**Comment by hoesman** [comment] 2023-05-20 15:25
Yeah I just figured that out now, I can view only my matched profiles via /user/_ID, the ids are real but restricted to matches. RIP stalkers :)

**Comment by anilabhadatta** [comment] 2023-05-20 15:49
> > @JustixDevelopment https://github.com/ecole96/TinderUnblur/tree/master refer to this repo, it is working
> 
> well this is because this is using a different approach to unblur the images, this will only work for 1 image though, I could implement that using the following code: `teaserEl.style.backgroundImage = `[https://preview.gotinder.com/${teaser.user._id}/original_${teaser.user.photos[0].id}.jpeg`;`](https://preview.gotinder.com/$%7Bteaser.user._id%7D/original_$%7Bteaser.user.photos%5B0%5D.id%7D.jpeg%60;%60)

I tried that extension and it unblurred all the images that were in my Liked section

**Comment by jgeramb** [comment] 2023-05-20 15:54
> > > @JustixDevelopment https://github.com/ecole96/TinderUnblur/tree/master refer to this repo, it is working
> > 
> > 
> > well this is because this is using a different approach to unblur the images, this will only work for 1 image though, I could implement that using the following code: `teaserEl.style.backgroundImage = `[https://preview.gotinder.com/${teaser.user._id}/original_${teaser.user.photos[0].id}.jpeg`;`](https://preview.gotinder.com/$%7Bteaser.user._id%7D/original_$%7Bteaser.user.photos%5B0%5D.id%7D.jpeg%60;%60)
> 
> I tried that extension and it unblurred all the images that were in my Liked section

yes that is exactly what I meant, it unblurres 1 photo per user (like), but you cannot see the name, other photos etc.

**Comment by anilabhadatta** [comment] 2023-05-20 16:44
@JustixDevelopment https://github.com/orknist/tinder-deblur-gold/blob/main/tinder.user.js
Found this script where clicking the heart emoji matches automatically. Is there any way to get the username from this implementation?

**Comment by jgeramb** [comment] 2023-05-21 09:40
@anilabhadatta no, but I made a workaround for the API changes, though we just have one unblurred image and the like/pass functions now, the name, age, distance etc. are gone for now.

**Comment by tajnymag** [comment] 2023-05-21 14:22
Guys, can you try the development version again? Justix came up with a workaround for the API changes.

https://raw.githubusercontent.com/tajnymag/tinder-deblur/develop/tinder.user.js

**Comment by naoliv** [comment] 2023-05-21 14:33
> Guys, can you try the development version again? Justix came up with a workaround for the API changes.
> 
> https://raw.githubusercontent.com/tajnymag/tinder-deblur/develop/tinder.user.js

It's displaying the pictures again, but dismissing/matching isn't working.

**Comment by jgeramb** [comment] 2023-05-21 16:19
> It's displaying the pictures again, but dismissing/matching isn't working.

@naoliv that will work again upon merging #36

**Comment by tajnymag** [comment] 2023-05-21 16:22
Merged

**Comment by gavracone** [comment] 2023-05-21 17:02
Cleared cache and cookies.
I have 9 likes.
Today i received one like. I cant  see that picture, i get "invalid" error
I see rest of likes, i dismiss them but upon next refresh, i see them again.

**Comment by imongithub123** [comment] 2023-05-21 17:05
I see the first photo of my likes. That’s about it. Good stuff though
either way guys

**Comment by jgeramb** [comment] 2023-05-22 08:43
> Cleared cache and cookies.
> I have 9 likes.
> Today i received one like. I cant see that picture, i get "invalid" error
> I see rest of likes, i dismiss them but upon next refresh, i see them again.

the second issue should be fixed with the current file, the "invalid" image simply means that it cannot be unblurred because the image url doesn't contain enough information, you can send the image url in here though and I'll try to find a way to unblur it

**Comment by jgeramb** [comment] 2023-05-25 13:09
I think this issue can also be closed since the initial issue is resolved. @tajnymag

**Closed as completed** 2023-05-25 13:26 UTC
Labels: bug
